# Generated by Django 6.0.7 on 2026-07-17 15:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('established_date', models.DateField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('vat_registered_date', models.DateField(blank=True, null=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('website', models.TextField(blank=True, null=True)),
                ('business_address', models.JSONField(blank=True, null=True)),
                ('business_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('business_city', models.TextField(blank=True, null=True)),
                ('business_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_address', models.JSONField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('institutional_sector_code', models.CharField(blank=True, max_length=20, null=True)),
                ('institutional_sector_name', models.TextField(blank=True, null=True)),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('is_registered_business_register', models.BooleanField(default=False)),
                ('is_registered_foundation', models.BooleanField(default=False)),
                ('is_registered_voluntary', models.BooleanField(default=False)),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('is_under_liquidation', models.BooleanField(default=False)),
                ('is_under_forced_liquidation', models.BooleanField(default=False)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_number', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deletion_requests',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('parent_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('municipality_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'organization_types',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_types',
            },
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_number', models.CharField(max_length=9, unique=True)),
                ('name', models.TextField()),
                ('website', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('business_address', models.JSONField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_address', models.JSONField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='myapi.company')),
                ('organization_type', models.ForeignKey(db_column='organization_type_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.organizationtype')),
            ],
            options={
                'db_table': 'company_locations',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='organization_type',
            field=models.ForeignKey(db_column='organization_type_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.organizationtype'),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='myapi.company')),
                ('holding_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_roles', to='myapi.company')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.person')),
                ('role_type', models.ForeignKey(db_column='role_type_code', on_delete=django.db.models.deletion.CASCADE, to='myapi.roletype')),
            ],
            options={
                'db_table': 'company_roles',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_number', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_year', models.IntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='NOK', max_length=3)),
                ('accounting_type', models.CharField(blank=True, max_length=10, null=True)),
                ('statement_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('is_liquidation_statement', models.BooleanField(default=False)),
                ('is_small_business', models.BooleanField(default=False)),
                ('accounting_rules', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_exempt', models.BooleanField(default=False)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
                ('operating_revenue', models.BigIntegerField(blank=True, null=True)),
                ('operating_profit', models.BigIntegerField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='myapi.company')),
            ],
            options={
                'db_table': 'financial_statements',
                'unique_together': {('company', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='myapi.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.industry')),
            ],
            options={
                'db_table': 'company_industries',
                'unique_together': {('company', 'industry')},
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='companies_search__ec0013_gin'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['employee_count', 'registered_date'], name='companies_employe_7ff94f_idx'),
        ),
    ]
