# Generated by Django 6.0.7 on 2026-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['financial_year', 'operating_revenue'], name='financial_s_financi_17a2d9_idx'),
        ),
    ]
